### ISSUE TITLE
Build fails when trying digest changes from `eo` v0.29.4.

### ISSUE THREAD

**Issue by mximp** [objectionary/home#126]
Trying to pull changes into Home from `objectionary/eo` (v0.29.4).
On branch from home/master execute:
```shell
./pull.sh objectionary/eo
make clean; make
```
Build error:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   EOgets_lengths_of_empty_tuple_keywordTest.testWorks:59->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255 » Ex EOorg.EOeolang.EOstringν90="Error at "EOorg.EOeolang.EOhamcrest.EOassert_that#actual" attribute; caused by The object is at the line #188, position #4 within `?`; caused by ExUnset: Error at "EOorg.EOeolang.EOtuple#empty" attribute; caused by ExUnset: Can't get(), attribute "empty" is absent among other 6 attrs (length, ρ, with, σ, at, Δ) and φ is absent"SF
[ERROR]   EOtuple_fluent_with_indented_keywordTest.testWorks:120->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256 » Ex EOorg.EOeolang.EOstringν2138="Error at "EOorg.EOeolang.EOcollections.EOlist#arr" attribute; caused by The object is at the line #192, position #2 within `?`; caused by ExUnset: Error at "EOorg.EOeolang.EOtuple#empty" attribute; caused by ExUnset: Can't get(), attribute "empty" is absent among other 6 attrs (length, ρ, with, σ, at, Δ) and φ is absent"SF
```

**Comment by mximp** [comment]
Full stack trace:
```
[ERROR] EOorg.EOeolang.EOgets_lengths_of_empty_tuple_keywordTest.testWorks  Time elapsed: 0.15 s  <<< ERROR!
EOorg.EOeolang.EOerror$ExError: EOorg.EOeolang.EOstringν90="Error at "EOorg.EOeolang.EOhamcrest.EOassert_that#actual" attribute; caused by The object is at the line #188, position #4 within `?`; caused by ExUnset: Error at "EOorg.EOeolang.EOtuple#empty" attribute; caused by ExUnset: Can't get(), attribute "empty" is absent among other 6 attrs (length, ρ, with, σ, at, Δ) and φ is absent"SF
	at org.eolang.AtSafe.get(AtSafe.java:72)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.equals(PhOnce.java:61)
	at org.eolang.PhMethod.equals(PhMethod.java:32)
	at org.eolang.PhLocated.equals(PhLocated.java:83)
	at org.eolang.PhConst.equals(PhConst.java:60)
	at org.eolang.PhNamed.equals(PhNamed.java:57)
	at org.eolang.PhSafe.equals(PhSafe.java:52)
	at org.eolang.PhImmovable.equals(PhImmovable.java:50)
	at org.eolang.PhOnce.equals(PhOnce.java:61)
	at org.eolang.PhMethod.equals(PhMethod.java:32)
	at org.eolang.PhLocated.equals(PhLocated.java:83)
	at org.eolang.AtFree.get(AtFree.java:114)
	at org.eolang.AtNamed.get(AtNamed.java:95)
	at org.eolang.AtSafe.get(AtSafe.java:69)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.equals(PhOnce.java:61)
	at org.eolang.PhMethod.equals(PhMethod.java:32)
	at org.eolang.PhLocated.equals(PhLocated.java:83)
	at org.eolang.AtFree.get(AtFree.java:114)
	at org.eolang.AtNamed.get(AtNamed.java:95)
	at org.eolang.AtSafe.get(AtSafe.java:69)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhConst.attr(PhConst.java:94)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.PhLocated.copy(PhLocated.java:107)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:86)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.Dataized.take(Dataized.java:97)
	at EOorg.EOeolang.EObool$EOand.lambda$new$0(EObool$EOand.java:67)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:255)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.PhLocated.copy(PhLocated.java:107)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:86)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:86)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:89)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.PhLocated.copy(PhLocated.java:107)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:86)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:86)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.PhLocated.attr(PhLocated.java:117)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.Dataized.take(Dataized.java:97)
	at EOorg.EOeolang.EOgets_lengths_of_empty_tuple_keywordTest.testWorks(EOgets_lengths_of_empty_tuple_keywordTest.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by mximp** [comment]
@volodya-lombrozo That seems to be affected by tuple changes - have you seen this before?

**Comment by volodya-lombrozo** [comment]
@mximp I haven't seen that and I'm not sure about `tuple` changes here. Apparently, we have to investigate the problem.

**Comment by mximp** [comment]
Solution: remove `tests/org/eolang/collections/array-tests.eo`.

Due to unknown reason the file was not removed when arrays were replaced with tuples.
